version: "3.8"

services:
  my_application:
    build: .
    ports:
      - "3001:3001" # Port for backend (or frontend, based on your setup)
      - "8081:8081" # Port for frontend (or backend, based on your setup)
    command: >
      sh -c "mosquitto -d &&
             cd backend && npm start &
             cd .. & cd frontend && npm run start"

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883" # Default MQTT port
      - "9001:9001" # Default WebSocket port for MQTT
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
