version: "3.8"

services:
  my_application:
    build: .
    ports:
      - "3001:3001" # Port for backend (if needed)
      - "8081:8081" # Port for frontend (if needed)
      - "5000:5000" # Port for Flask server
    command: >
      sh -c "mosquitto -d &&
             cd backend && npm start &
             cd .. & cd frontend && npm run start &
             cd python && ./venv/bin/python main.py"

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883" # Default MQTT port
      - "9001:9001" # Default WebSocket port for MQTT
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
