version: "3.8"

services:
  my_application:
    build: .
    ports:
      - "3001:3001"
      - "8081:8081"
      - "1883:1883"
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 512M
    command:
      [
        "sh",
        "-c",
        "cd backend && npm start & cd .. & cd frontend && npm run start",
      ]
