name: Build Backend

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    if: ${{ github.event.label.name == 'ready' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: backend
          mode: build

      - name: Install dependencies
        run: |
          npm ci
          npm audit --production
          npm run lint # Optional: Run linter to ensure code quality

      - name: Run tests
        run: |
          npm test
          # Consider additional steps for end-to-end tests if applicable

      - name: Start server
        run: |
          npm start &
          sleep 3 # Wait for server to start
          curl -I http://localhost:3001 # Test server health
