name: Build Backend

on:
  pull_request: # Run on pull requests to master
    branches:
      - master
    types:
      - labeled

jobs:
  build:
    if: ${{ github.event.label.name == 'ready' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: backend
          mode: build

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Start server
        run: npm start