name: Build Backend2

on:
  pull_request:
  push: 
    branches: 
      - master

jobs:
  setup-environment:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd backend
          touch error_log.txt
          npm install > install_log.txt 2>&1 || echo "Error during npm install" > error_log.txt
          npm audit --production >> install_log.txt 2>&1 || echo "Error during npm audit" >> error_log.txt
          npm run lint >> install_log.txt 2>&1 || echo "Error during linting" >> error_log.txt # Optional: Run linter to ensure code quality

      - name: Install frontend dependencies
        run: |
          cd frontend
          touch error_log.txt
          npm install > install_log.txt 2>&1 || echo "Error during npm install" > error_log.txt
          npm install --global expo-cli >> install_log.txt 2>&1 || echo "Error during expo-cli install" >> error_log.txt
          npm audit --production >> install_log.txt 2>&1 || echo "Error during npm audit" >> error_log.txt
          npm run lint >> install_log.txt 2>&1 || echo "Error during linting" >> error_log.txt # Optional: Run linter to ensure code quality

      - name: Error msg
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: errors
          path: backend/error_log.txt
          if-no-files-found: ignore

  run-tests:
    runs-on: self-hosted
    needs: setup-environment
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Checkout error log
        uses: actions/download-artifact@v3
        with:
          name: errors    

      - name: Run tests and capture output
        run: |
          if [ -s backend/error_log.txt ]; then
            echo "Env not set up correctly"
            cat backend/error_log.txt
            exit 1
          else
            echo "Code testing"
          fi

      - name: Run backend tests
        run: |
          cd backend
          npm test

      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      - name: Start backend server
        run: |
          cd backend
          npm start &
          sleep 3
          curl -I http://localhost:3001 # Test backend server health

      - name: Start frontend server
        run: |
          cd frontend
          expo start --no-interactive &
          sleep 3
          curl -I http://localhost:8081 # Test frontend server health
