name: Build Backend2

on:
  pull_request:
  push: 
    branches: 
      - master


jobs:
  build:
    if: ${{ github.event.label.name == 'ready' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd backend
          npm install
          npm audit --production
          npm run lint # Optional: Run linter to ensure code quality

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
          npm install --global expo-cli
          npm audit --production
          npm run lint # Optional: Run linter to ensure code quality

      - name: Run backend tests
        run: |
          cd backend
          npm test

      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      - name: Start backend server
        run: |
          cd backend
          npm start &
          sleep 3
          curl -I http://localhost:3001 # Test backend server health

      - name: Start frontend server
        run: |
          cd frontend
          expo start --no-interactive &
          sleep 3
          curl -I http://localhost:8081 # Test frontend server health
